[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://kwikapp.netlify.app"
  to = "https://www.kwik.se/"
  status = 301
  force = true

[[redirects]]
  from = "https://kwikapp.netlify.app/*"
  to = "https://www.kwik.se/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
  Link = "<https://www.kwik.se>; rel='canonical'"