import fs from 'node:fs/promises'
import { dataPath } from './utils'

export async function generatePostIndex() {
  const fileNames = (await fs.readdir(dataPath('/posts'), { withFileTypes: true }))
    .filter((entry) => entry.isFile() && entry.name.endsWith('.json'))
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b))

  const imports = fileNames.map(
    (fileName, index) => `import post${index} from ${JSON.stringify(`./posts/${fileName}`)}`,
  )

  const entries = fileNames.map(
    (fileName, index) => `  { fileName: ${JSON.stringify(fileName)}, data: post${index} },`,
  )

  return [
    '// This file is generated by scripts/generate-post-index.ts. Do not edit it manually.',
    ...imports,
    '',
    'export const POST_SOURCES = [',
    ...entries,
    '] as const',
    '',
  ].join('\n')
}
