// This file is generated by scripts/generate-post-index.ts. Do not edit it manually.
import post0 from "./posts/a-boilerplate-node-js-config-2022-12-24.json"
import post1 from "./posts/blogs-to-follow-2022-11-23.json"
import post2 from "./posts/bra-gratis-verktyg-att-lyxa-till-presentationen-2026-05-20.json"
import post3 from "./posts/can-your-variable-be-multiple-types-use-a-ternary-operator-in-your-jsx-2022-12-23.json"
import post4 from "./posts/change-color-on-an-svg-with-css-2024-01-04.json"
import post5 from "./posts/cloudflared-tunnels-låter-mig-komma-ut-på-internet-när-telia-inte-gör-det-2026-05-26.json"
import post6 from "./posts/cors-issues-use-a-proxy-2022-11-30.json"
import post7 from "./posts/css-har-inbyggd-scope-2026-05-16.json"
import post8 from "./posts/det-går-ej-att-själv-referera-i-ett-oinitierat-objekt-2022-12-01.json"
import post9 from "./posts/ekonomiska-visord.json"
import post10 from "./posts/es6-way-to-read-absolute-path-node-js-2023-01-06.json"
import post11 from "./posts/free-email-hosting-with-own-domain-using-zoho-mail-2023-12-21.json"
import post12 from "./posts/hitta-specifik-förfader-med-rekursion-2023-01-03.json"
import post13 from "./posts/höjden-100vh-gäller-inte-på-iphones-använd-webkit-fill-available-2023-01-04.json"
import post14 from "./posts/iconify-en-open-source-bibliotek-av-ikoner-2022-12-29.json"
import post15 from "./posts/importera-med-ett-alias-till-sökvägen-istället-för-..-2026-06-01.json"
import post16 from "./posts/importing-dotenv-the-es6-modules-way-2022-12-15.json"
import post17 from "./posts/reactrouter-fungerar-inte-med-hashade-länkar-2022-11-24.json"
import post18 from "./posts/reacts-createportal-får-dom-element-att-teleportera-2022-12-23.json"
import post19 from "./posts/scss-är-ett-bättre-css-2022-11-26.json"
import post20 from "./posts/share-types-between-backend-and-frontend-in-a-monorepo-2022-12-29.json"
import post21 from "./posts/share-variables-between-middlewares-in-express-2022-12-28.json"
import post22 from "./posts/show-unicode-pairs-as-icon-by-using-fromcodepoint-2022-11-24.json"
import post23 from "./posts/skapa-en-relativ-sökväg-av-enbart-filnamnet-2022-11-23.json"
import post24 from "./posts/skapa-unika-strängar-med-crypto-2023-01-16.json"
import post25 from "./posts/snap-a-user-scroll-smoothly-to-specific-points-with-css-2023-01-03.json"
import post26 from "./posts/transform-a-breadcrumbs-string-into-a-parent-linked-data-structure-2023-01-11.json"
import post27 from "./posts/undraw-en-open-source-bibliotek-av-svg-illustrationer-2022-12-19.json"
import post28 from "./posts/urlsearchparams-converts-javascript-data-types-into-a-url-encoded-string-2023-01-04.json"
import post29 from "./posts/use-obj-variable-without-typescript-causing-an-issue-with-type-assertion-2024-01-12.json"
import post30 from "./posts/usecontext-i-react-för-ljus-mörk-tema-2022-11-29.json"
import post31 from "./posts/using-middleware-in-express-2022-12-28.json"
import post32 from "./posts/visa-upp-en-självöversatt-och-formaterad-lista-med-intl-listformat-2022-12-02.json"
import post33 from "./posts/vue-share-data-between-child-and-parent-2022-11-25.json"
import post34 from "./posts/zod-is-a-one-stop-solution-to-validate-and-type-declare-your-data-2022-12-16.json"

export const POST_SOURCES = [
  { fileName: "a-boilerplate-node-js-config-2022-12-24.json", data: post0 },
  { fileName: "blogs-to-follow-2022-11-23.json", data: post1 },
  { fileName: "bra-gratis-verktyg-att-lyxa-till-presentationen-2026-05-20.json", data: post2 },
  { fileName: "can-your-variable-be-multiple-types-use-a-ternary-operator-in-your-jsx-2022-12-23.json", data: post3 },
  { fileName: "change-color-on-an-svg-with-css-2024-01-04.json", data: post4 },
  { fileName: "cloudflared-tunnels-låter-mig-komma-ut-på-internet-när-telia-inte-gör-det-2026-05-26.json", data: post5 },
  { fileName: "cors-issues-use-a-proxy-2022-11-30.json", data: post6 },
  { fileName: "css-har-inbyggd-scope-2026-05-16.json", data: post7 },
  { fileName: "det-går-ej-att-själv-referera-i-ett-oinitierat-objekt-2022-12-01.json", data: post8 },
  { fileName: "ekonomiska-visord.json", data: post9 },
  { fileName: "es6-way-to-read-absolute-path-node-js-2023-01-06.json", data: post10 },
  { fileName: "free-email-hosting-with-own-domain-using-zoho-mail-2023-12-21.json", data: post11 },
  { fileName: "hitta-specifik-förfader-med-rekursion-2023-01-03.json", data: post12 },
  { fileName: "höjden-100vh-gäller-inte-på-iphones-använd-webkit-fill-available-2023-01-04.json", data: post13 },
  { fileName: "iconify-en-open-source-bibliotek-av-ikoner-2022-12-29.json", data: post14 },
  { fileName: "importera-med-ett-alias-till-sökvägen-istället-för-..-2026-06-01.json", data: post15 },
  { fileName: "importing-dotenv-the-es6-modules-way-2022-12-15.json", data: post16 },
  { fileName: "reactrouter-fungerar-inte-med-hashade-länkar-2022-11-24.json", data: post17 },
  { fileName: "reacts-createportal-får-dom-element-att-teleportera-2022-12-23.json", data: post18 },
  { fileName: "scss-är-ett-bättre-css-2022-11-26.json", data: post19 },
  { fileName: "share-types-between-backend-and-frontend-in-a-monorepo-2022-12-29.json", data: post20 },
  { fileName: "share-variables-between-middlewares-in-express-2022-12-28.json", data: post21 },
  { fileName: "show-unicode-pairs-as-icon-by-using-fromcodepoint-2022-11-24.json", data: post22 },
  { fileName: "skapa-en-relativ-sökväg-av-enbart-filnamnet-2022-11-23.json", data: post23 },
  { fileName: "skapa-unika-strängar-med-crypto-2023-01-16.json", data: post24 },
  { fileName: "snap-a-user-scroll-smoothly-to-specific-points-with-css-2023-01-03.json", data: post25 },
  { fileName: "transform-a-breadcrumbs-string-into-a-parent-linked-data-structure-2023-01-11.json", data: post26 },
  { fileName: "undraw-en-open-source-bibliotek-av-svg-illustrationer-2022-12-19.json", data: post27 },
  { fileName: "urlsearchparams-converts-javascript-data-types-into-a-url-encoded-string-2023-01-04.json", data: post28 },
  { fileName: "use-obj-variable-without-typescript-causing-an-issue-with-type-assertion-2024-01-12.json", data: post29 },
  { fileName: "usecontext-i-react-för-ljus-mörk-tema-2022-11-29.json", data: post30 },
  { fileName: "using-middleware-in-express-2022-12-28.json", data: post31 },
  { fileName: "visa-upp-en-självöversatt-och-formaterad-lista-med-intl-listformat-2022-12-02.json", data: post32 },
  { fileName: "vue-share-data-between-child-and-parent-2022-11-25.json", data: post33 },
  { fileName: "zod-is-a-one-stop-solution-to-validate-and-type-declare-your-data-2022-12-16.json", data: post34 },
] as const
