site_url: https://www.kwik.se/
locale: 'sv'

backend:
  name: github
  repo: kwiknordic/kwik.se
  branch: main
  auth_endpoint: https://sveltia-cms-auth.pages.dev/auth
  app_id: Ov23liXROaCRpqJa5ilk

media_folder: '/src/cms/uploads/'
public_folder: '/public/uploads'

collections:
  - label: 'Blogg'
    name: 'blogg'
    folder: '/src/data/posts/'
    create: true
    slug: '{{slug}}-{{year}}-{{month}}-{{day}}'
    extension: 'json'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Publicering', name: 'date', widget: 'datetime' }
      - { label: 'Ämne', name: 'title', widget: 'string' }
      - { label: 'Innehåll', name: 'body', widget: 'markdown' }
      - { label: 'Språk', name: 'language', widget: 'select', options: ['sv', 'en'], default: 'sv' }
