site_url: https://kwik.se
display_url: https://kwik.se
locale: 'sv'

backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "/src/cms/uploads/"
public_folder: "/public/uploads"

collections:
  - name: "blogg" # Used in routes, e.g., /admin/collections/blog
    label: "Blogg" # Used in the UI
    folder: "/src/cms/_posts/blog" # The path to the folder where the documents are stored
    create: true
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "html"
    format: "json"
    filter: {field: "language", value: "sv"}
    fields: # The fields for each document, usually in front matter
      - {label: "Språk", name: "language", widget: "select", options: ["sv", "en"]}
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Ämne", name: "title", widget: "string"}
      - {label: "Publiceringsdag", name: "date", widget: "datetime"}
      - {label: "Innehåll", name: "body", widget: "text"}
    - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "/src/cms/_posts/blog" # The path to the folder where the documents are stored
    create: true
    slug: "{{slug}}-{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: "html"
    format: "json"
    filter: {field: "language", value: "en"}
    fields: # The fields for each document, usually in front matter
      - {label: "Language", name: "language", widget: "select", options: ["sv", "en"]}
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish", name: "date", widget: "datetime"}
      - {label: "Content", name: "body", widget: "text"}